data(airquality)
summary(airquality)
melted_airquality <- melt(airquality, id.vars = c("Month", "Day"))
head(melted_airquality)
melted_airquality <- melt(airquality, id.vars = c("Month", "Day"))
head(melted_airquality)
casted_airquality <- dcast(melted_airquality, Month + Day ~ variable)
head(casted_airquality)
averages_airquality <- dcast(melted_airquality, Month ~ variable, mean)
head(averages_airquality)
